# Generated by Django 5.0.14 on 2026-05-09 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_code', models.CharField(max_length=64, unique=True, verbose_name='资产编号')),
                ('name', models.CharField(max_length=120, verbose_name='资产名称')),
                ('category', models.CharField(max_length=80, verbose_name='资产类型')),
                ('location', models.CharField(max_length=120, verbose_name='所在位置')),
                ('owner', models.CharField(blank=True, max_length=80, verbose_name='责任人')),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '预警'), ('fault', '故障'), ('offline', '离线')], default='normal', max_length=32, verbose_name='运行状态')),
                ('last_inspection_at', models.DateTimeField(blank=True, null=True, verbose_name='最近巡检时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_no', models.CharField(max_length=64, unique=True, verbose_name='任务编号')),
                ('title', models.CharField(max_length=160, verbose_name='任务标题')),
                ('scheduled_date', models.DateField(verbose_name='计划日期')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '执行中'), ('completed', '已完成'), ('overdue', '已逾期')], default='pending', max_length=32, verbose_name='任务状态')),
                ('result', models.CharField(choices=[('unchecked', '未提交'), ('normal', '正常'), ('abnormal', '异常')], default='unchecked', max_length=32, verbose_name='巡检结果')),
                ('result_summary', models.TextField(blank=True, verbose_name='结果说明')),
                ('exception_note', models.TextField(blank=True, verbose_name='异常说明')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='operations.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_tasks', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_tasks',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_no', models.CharField(max_length=64, unique=True, verbose_name='故障编号')),
                ('title', models.CharField(max_length=160, verbose_name='故障标题')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=32, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('closed', '已关闭')], default='open', max_length=32, verbose_name='处理状态')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('solution', models.TextField(blank=True, verbose_name='处理方案')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_reports', to='operations.asset')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_reports', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='operations.inspectiontask')),
            ],
            options={
                'db_table': 'fault_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=160, verbose_name='告警标题')),
                ('source_type', models.CharField(default='巡检异常', max_length=80, verbose_name='来源类型')),
                ('level', models.CharField(choices=[('info', '提示'), ('warning', '预警'), ('critical', '严重')], default='warning', max_length=32, verbose_name='告警级别')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('closed', '已关闭')], default='pending', max_length=32, verbose_name='处理状态')),
                ('content', models.TextField(verbose_name='告警内容')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handling_note', models.TextField(blank=True, verbose_name='处理说明')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_alerts', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='operations.asset')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='operations.inspectiontask')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80, verbose_name='模块')),
                ('action', models.CharField(max_length=80, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, max_length=80, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=80, verbose_name='对象ID')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('duty_date', models.DateField(verbose_name='值班日期')),
                ('shift_name', models.CharField(max_length=80, verbose_name='班次')),
                ('status', models.CharField(choices=[('scheduled', '已排班'), ('on_duty', '值班中'), ('off_duty', '已交班')], default='scheduled', max_length=32, verbose_name='值班状态')),
                ('notes', models.TextField(blank=True, verbose_name='值班记录')),
                ('duty_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_rosters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duty_rosters',
                'ordering': ['-duty_date', 'shift_name'],
                'unique_together': {('duty_date', 'shift_name', 'duty_user')},
            },
        ),
    ]
